{"status": "passed", "labels": [{"name": "story", "value": "账户、密码输入错误用例"}, {"name": "feature", "value": "登录用例"}, {"name": "tag", "value": "run(order=2)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('init_driver', 'setup')"}, {"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "webtest.testcases"}, {"name": "suite", "value": "test_loginpytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "cnki-PC"}, {"name": "thread", "value": "632648-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "webtest.testcases.test_loginpytest"}], "parameters": [{"name": "data", "value": "{'expected': '此账号没有经过授权，请联系管理员!', 'pwd': 'python1', 'phone': '18810444950'}"}], "fullName": "webtest.testcases.test_loginpytest.TestLogin#test_login_2", "name": "test_login_2[data0]", "stop": 1594457983022, "historyId": "14742b3a38a9a067917d8b58c5c4f3e3", "start": 1594457982047, "testCaseId": "4de8035ea60fcdf87d07e0a66f2d92ca", "uuid": "72033955-950c-4208-bc7d-4f8c1eb4672c"}